# Generated by Django 2.2 on 2020-06-26 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Severe_Pollution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(blank=True)),
                ('dist', models.TextField(blank=True)),
                ('loc', models.TextField(blank=True)),
                ('count_people', models.IntegerField()),
                ('have_seniors', models.BooleanField()),
                ('have_specials', models.BooleanField()),
                ('specify_specials', models.TextField(blank=True)),
                ('have_policies', models.BooleanField()),
                ('have_hard_cpy', models.BooleanField()),
                ('have_masks', models.BooleanField()),
                ('have_air_purifier', models.BooleanField()),
                ('have_check_quality', models.BooleanField()),
                ('have_cardiac', models.BooleanField()),
                ('have_medicines', models.BooleanField()),
                ('have_CO_detector', models.BooleanField()),
                ('CO_off', models.TextField(blank=True)),
                ('response', models.TextField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
