# Generated by Django 2.2 on 2020-06-26 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_Insured',
        ),
    ]
